# Generated by Django 4.2.19 on 2025-08-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employerprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='about',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
