# Generated by Django 4.2.19 on 2025-08-24 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=300)),
                ('job_type', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=150)),
                ('job_description', models.TextField(blank=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employerprofile')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
