# Generated by Django 4.2.19 on 2025-08-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('interviewing', 'Interviewing'), ('completed', 'Completed')], default='active', max_length=20),
        ),
    ]
