# Generated by Django 4.2.19 on 2025-08-26 04:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobapplied'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplied',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplied',
            name='availability',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplied',
            name='cover_letter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplied',
            name='desired_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='jobapplied',
            name='referral',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobapplied',
            name='resume',
            field=models.FileField(null=True, upload_to='resumes/'),
        ),
    ]
