# Generated by Django 4.2.19 on 2025-08-26 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobapplied_additional_notes_jobapplied_availability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplied',
            name='resume',
        ),
    ]
