# Generated by Django 4.2.19 on 2025-08-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_jobapplied_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='benefits',
            field=models.JSONField(default=list, help_text='A list of company benefits offered for the position.'),
        ),
        migrations.AddField(
            model_name='job',
            name='qualifications',
            field=models.JSONField(default=list, help_text='A list of required qualifications and skills.'),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.JSONField(default=list, help_text="A list of the job's key responsibilities."),
        ),
    ]
